# Generated by Django 3.1.2 on 2020-11-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20201117_1111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchhistorymodel',
            name='date1',
            field=models.CharField(blank=True, max_length=30, verbose_name='1940-01-01'),
        ),
        migrations.AlterField(
            model_name='searchhistorymodel',
            name='date2',
            field=models.CharField(blank=True, max_length=30, verbose_name='2020-01-01'),
        ),
    ]
